package de.hpi.semrecsys;

// default package
// Generated Aug 12, 2014 6:25:02 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SimilarProductId generated by hbm2java
 */
@Embeddable
public class RecommendationId implements java.io.Serializable {

    private int productId;
    private int position;
    private int linkedProductId;

    public RecommendationId() {
    }

    public RecommendationId(int productId, int position,
                            int linkedProductId) {
        this.productId = productId;
        this.position = position;
        this.linkedProductId = linkedProductId;
    }

    @Column(name = "product_id", nullable = false)
    public int getProductId() {
        return this.productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    @Column(name = "position", nullable = false)
    public int getPosition() {
        return this.position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    @Column(name = "linked_product_id", nullable = false)
    public int getLinkedProductId() {
        return this.linkedProductId;
    }

    public void setLinkedProductId(int linkedProductId) {
        this.linkedProductId = linkedProductId;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof RecommendationId))
            return false;
        RecommendationId castOther = (RecommendationId) other;

        return (this.getProductId() == castOther.getProductId())
                && (this.getPosition() == castOther.getPosition())
                && (this.getLinkedProductId() == castOther.getLinkedProductId());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getProductId();
        result = 37 * result + this.getPosition();
        result = 37 * result + this.getLinkedProductId();
        return result;
    }

}
